name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          cat <<'EOF' | envsubst > release.md
          # pinit ${TAG_NAME}
          ## Installation
          ```bash
          git clone https://github.com/enuesaa/pinit.git -b ${TAG_NAME} --depth 1
          cd pinit
          go install
          ```
          EOF

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body_path: release.md
